### PR TITLE
merge from Nvidia main

### PR DESCRIPTION
**Pull request by RaymondLi0**

### CODE REVIEW

**Comment by mayank31398** [comment]
Hey @RaymondLi0 , thanks a lot for this effort.
Any ETA on this?

**Comment by RaymondLi0** [comment]
Hopefully early next week :)

**Comment by RaymondLi0** [comment]
Some things are broken (I created a branch named `before-merge`, in case someone wants to do one of these):
- loading previous checkpoints that used the distributed optimizer will not work
- the checkpoint merging tools will not work on previous checkpoints (may be fixed later with another merge from NVIDIA's repo)

**Review by jlamypoirier — APPROVED** [review]
Let's just merge and hope for the best 🤷‍♂️

**Pull request merged**
